Repository itaouo/OOPL_CandyCrush, pull requests merged in 2024-03, with the labels that each got.

#2 Adjust resolution and README
  README.md
  Resources/texture_pack_original/bg_screens/2.bmp
  Source/Game/config.h
  Source/Game/mygame_initialize.cpp
Labels: documentation, enhancement

#3 edit candy image and place init candy
  Resources/texture_pack_original/candy/blue.bmp
  Resources/texture_pack_original/candy/green.bmp
  Resources/texture_pack_original/candy/orange.bmp
  Resources/texture_pack_original/candy/purple.bmp
  Resources/texture_pack_original/candy/red.bmp
  Resources/texture_pack_original/candy/yellow.bmp
  Source/Game/mygame.h
  Source/Game/mygame_run.cpp
Labels: enhancement

#4 Import txt and transform to array
  Map/1.txt
  Resources/map/1.txt
  Source/Game/mygame_run.cpp
Labels: enhancement

#5 Fix read map error
  .vscode/settings.json
  Map/1.txt
  Resources/map/1.txt
  Resources/texture_pack_original/bg_screens/4.bmp
  Resources/texture_pack_original/bg_screens/4.jpg
  Source/Game/mygame_run.cpp
Labels: bug

#8 Repair candy
  Resources/texture_pack_original(old/candy/0.bmp
  Resources/texture_pack_original(old/candy/1.bmp
  Resources/texture_pack_original(old/candy/2.bmp
  Resources/texture_pack_original(old/candy/3.bmp
  Resources/texture_pack_original(old/candy/4.bmp
  Resources/texture_pack_original(old/candy/5.bmp
  Resources/texture_pack_original/bg_screens/0.bmp
  Resources/texture_pack_original/bg_screens/1.bmp
  Resources/texture_pack_original/bg_screens/2.bmp
  Resources/texture_pack_original/bg_screens/3.bmp
  Resources/texture_pack_original/candy/0.bmp
  Resources/texture_pack_original/candy/1.bmp
  Resources/texture_pack_original/candy/10.bmp
  Resources/texture_pack_original/candy/11.bmp
  Resources/texture_pack_original/candy/12.bmp
  Resources/texture_pack_original/candy/13.bmp
  Resources/texture_pack_original/candy/14.bmp
  Resources/texture_pack_original/candy/15.bmp
  Resources/texture_pack_original/candy/2.bmp
  Resources/texture_pack_original/candy/20.bmp
  Resources/texture_pack_original/candy/21.bmp
  Resources/texture_pack_original/candy/22.bmp
  Resources/texture_pack_original/candy/23.bmp
  Resources/texture_pack_original/candy/24.bmp
  Resources/texture_pack_original/candy/25.bmp
  Resources/texture_pack_original/candy/3.bmp
  Resources/texture_pack_original/candy/30.bmp
  Resources/texture_pack_original/candy/31.bmp
  Resources/texture_pack_original/candy/32.bmp
  Resources/texture_pack_original/candy/33.bmp
  Resources/texture_pack_original/candy/34.bmp
  Resources/texture_pack_original/candy/35.bmp
  Resources/texture_pack_original/candy/4.bmp
  Resources/texture_pack_original/candy/40.bmp
  Resources/texture_pack_original/candy/5.bmp
  Resources/texture_pack_original/candy/50.bmp
  Resources/texture_pack_original/icon.jpg
  Source/Game/mygame_run.cpp
Labels: bug

#9 Readme change
  README.md
Labels: documentation

#11 Swtich candy
  Resources/texture_pack_original/cursor.bmp
  Source/Game/mygame.h
  Source/Game/mygame_run.cpp
Labels: enhancement

#13 add the function of dropping candies
  Source/Game/mygame.h
  Source/Game/mygame_run.cpp
Labels: enhancement

#16 create_obstacle and restruct vertical_fall_candy, update_candy
  Resources/map/1.txt
  Resources/texture_pack_original/candy/-1.bmp
  Resources/texture_pack_original/candy/-11.bmp
  Source/Game/mygame.h
  Source/Game/mygame_run.cpp
Labels: enhancement

#18 Special candy
  .vscode/settings.json
  Source/Game/config.h
  Source/Game/mygame.h
  Source/Game/mygame_run.cpp
Labels: bug, enhancement

#21 finish Etype cnady, but have little bug
  Resources/map/1.txt
  Source/Game/mygame.h
  Source/Game/mygame_run.cpp
Labels: enhancement

#20 Cookies
  Resources/map/1.txt
  Resources/texture_pack_original/candy/-1.bmp
  Resources/texture_pack_original/candy/-10.bmp
  Resources/texture_pack_original/candy/-11.bmp
  Resources/texture_pack_original/candy/-12.bmp
  Resources/texture_pack_original/candy/-13.bmp
  Resources/texture_pack_original/candy/-99.bmp
  Source/Game/mygame.h
  Source/Game/mygame_run.cpp
Labels: bug, enhancement

#25 Special candy
  Resources/map/1.txt
  Resources/texture_pack_original/candy/7.bmp
  Source/Game/mygame_run.cpp
Labels: bug, enhancement
